modLoader="javafml" #mandatory

loaderVersion="[27,)" #mandatory (24 is current forge version)

credits="Thanks to Harry Talks for his amazing tutorials and Udemy for great Java courses." #optional

authors="kwpugh" #optional

[[mods]] #mandatory
modId="easy_steel" #mandatory
version="1.0.28" #mandatory
displayName="Easy Steel & More" #mandatory
description='''
Adds steel, bronze, and tungsten-carbide gear
'''


[[dependencies.easy_steel]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.easy_steel]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.3, 1.14.4]"
    ordering="NONE"
    side="BOTH"
